### PR TITLE
make sure we do not return undefined in arrays when not expected

### PR DESCRIPTION
**Pull request by mrousal**

### CODE REVIEW

**Comment by deregtd** [comment]
Most of these changes shouldn't be necessary.  InMemoryProvider likely has the bug there, but indexeddb will return elements from the index only if they exist from the getOnly call.  SQL is the same -- it will do a SELECT and only return any matching elements, so in neither of those should it be needed.  You shouldn't need to update the interface to T|undefined, just fix the one bug in InMemoryProvider and it should be all that's needed, right?

**Comment by mrousal** [comment]
Problem is that we have some crashes in HA which are caused by undefined being returned in arrays from DB queries, unfortunately we do not have logs for these so we do not have anything except JS stack. Last case was actually from getRange, but people already added couple of "compacts" to the app code so this has most likely happened before. 
We decided to "sanitize" all related API calls and Brent suggested that it should be preferably done here rather than in app code.

**Comment by mrousal** [comment]
I agree that "design wise" everything looks ok, but in real world undefined is somehow returned (rarely). Question is what is best fix while we do now know actual root cause now.

**Comment by deregtd** [comment]
Do you know for sure which provider(s) are causing the problem?  Is it definitely sqlproviderbase (and is it websql or react-native-sqlite) or is it potentially one of the others?  If we narrow it down a bit, I can do some more code reading to try to help identify.

**Pull request closed without merging**
